//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimeReviews.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimeList
    {
        public int id { get; set; }
        public string title { get; set; }
        public Nullable<int> episodes { get; set; }
        public string rating { get; set; }
    }
}
